# Generated by Django 3.1.5 on 2021-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('faction', models.CharField(choices=[('PD', '👮 Police Department 👮'), ('EMS', '🏥 Medical Department 🏥'), ('FBI', '🕵️ Federal Bureau Of Investigation(FBI) 🕵️'), (' Mech', '🛠️ Mechanic 🛠️'), ('News', '📰Department of News📰')], max_length=160)),
                ('qualification', models.CharField(max_length=200)),
                ('wtime', models.CharField(max_length=200)),
                ('exjob', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
