# Generated by Django 3.1.5 on 2021-08-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaform', '0003_remove_visamodel_textarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='visamodel',
            name='characterstory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='discordname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='igage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='iggender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='igname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='realage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='realname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='rpexp',
            field=models.CharField(choices=[('new', 'New to Roleplay'), ('1m', '1 Month'), ('5m', '5 months'), ('1y', '1 year'), ('a1y', 'Above 1 year')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visamodel',
            name='rprules',
            field=models.BooleanField(null=True),
        ),
    ]
