# Generated by Django 3.1.5 on 2021-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaform', '0006_visamodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visamodel',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
