# Generated by Django 3.1.5 on 2021-08-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visaform', '0009_auto_20210821_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visamodel',
            name='user',
        ),
    ]
