# Generated by Django 3.1.5 on 2021-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaform', '0011_visamodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visamodel',
            name='sender',
            field=models.CharField(max_length=100),
        ),
    ]
