# Generated by Django 3.1.5 on 2021-08-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visaform', '0013_auto_20210822_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visamodel',
            name='sender',
        ),
    ]
