# Generated by Django 3.1.5 on 2021-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaform', '0016_auto_20210822_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visamodel',
            name='username',
        ),
        migrations.AddField(
            model_name='visamodel',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
