# Generated by Django 3.1.5 on 2021-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visaform', '0017_auto_20210822_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='visamodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
