# Generated by Django 3.1.5 on 2021-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='Url',
            field=models.URLField(default='https://google.com/images'),
        ),
    ]
